import {type NextPage} from "next";
import Head from "next/head";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black  p-10">
        <div className="gradient ">
        </div>
        <div className="flex flex-col items-center justify-center w-full h-full absolute inset-0 top-10 gap-4
                shadow-2xl
                ">
          <h2 className="lg:text-5xl font-semibold text-white">
            Welcome to
          </h2>
          <h1 className="lg:text-8xl font-bold text-white">
            Unleashed
          </h1>
          <a className="text-2xl w-1/4 text-center">
            the social media platform that lets you unleash your creativity
          </a>
        </div>



      </main>
    </>
  );
};

export default Home;
